### ISSUE TITLE
Mission "A Surprise": Wrong Way-Points after Teleporting

### ISSUE THREAD

**Issue by BZdJunge** [BlackDragonN001/FERemastered#154]
When the AIs enter the teleporter they will try to re enter the same teleporter by going down the canyon again.

Usually, the own units will go to the base-nav after the teleportation. The enemies will only attack the Recycler after re entering the teleporter. This bug can be especially noticed by the south-east teleporter. If the Excavator is protected, the enemies from the nearby teleporter will attack the units instantly.

**Comment by BZdJunge** [comment]
Here some Screenshots:


![20220622231414_1](https://user-images.githubusercontent.com/107756798/176535700-ebcec5a9-0825-43ca-b533-09df194561ee.jpg)
![20220620000314_1](https://user-images.githubusercontent.com/107756798/176535714-7b5aa8e5-ae57-4863-87af-535233104e58.jpg)
![20220622230253_1](https://user-images.githubusercontent.com/107756798/176535745-187abf6e-9844-4200-987a-d011ef176665.jpg)
![20220622230343_1](https://user-images.githubusercontent.com/107756798/176535665-27a629ed-43f1-44d4-abfd-75433911cf39.jpg)

**Comment by BlackDragonN001** [comment]
This should be resolved, I redid the way units teleport through in mission.

**Comment by BZdJunge** [comment]
I tested this mission. Unfortunately this bug isn't fully resolved, yet.

One issue is the Recycler: it will go back to the teleporter, even when I immediately sented it to the Nav. Maybe this one can be solved, if the Recycler goes after the teleportation directly to the Nav-Point.

The own units provides no trouble. However, the hostiles will still fall down the cliff. Maybe it would help, when they attack the Recycler right after they teleported?

**Comment by BlackDragonN001** [comment]
ok, Redid how the lua script interacts with the Portal DLL code to properly override Goto orders, they should go where they are supposed to now after teleporting.

**Comment by BZdJunge** [comment]
The Recycler has still problems with the teleporter. It teleports right back. I believe the Recycler is too close to the teleporter and when it tries to path finding (turning) it hits the teleporter again.

**Comment by BZdJunge** [comment]
The Recycler has still a problem with teleporting back. I flied to its teleporter before the Recycler reached ist and noticed that it spawns  on the opposite direction (spawns to the eastern direction and also facing east). When it tries to turn it will teleported back.

**Comment by BZdJunge** [comment]
For the own units it works now properly, thanks you.

But the Hadeans have still some trouble: they often fly down the canyon again instead of going to the Recycler. So it seems to be inconsistent. They also spawn relatively rare (4 to 5 minutes). I cannot remember this long spawn rate in the vanilla version

**Comment by GraveyBoi** [comment]
I remember it building up slowly, the pacing does feel a bit slow for an experienced player.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GraveyBoi** [comment]
I think I could work on this second half a bit and speed it up like I did for mission 1.
